(defun fzf--sentinel (process event)
  (let ((buffer (process-buffer process)))
    (when (and buffer (local-variable-p 'fzf--filename buffer))
      (let ((path (buffer-local-value 'fzf--path buffer))
            (tmp-filename (buffer-local-value 'fzf--filename buffer)))
        (kill-buffer buffer)
        (dolist (filename (utils--read-lines tmp-filename))
          (find-file (concat (file-name-as-directory path) filename)))
        (delete-file tmp-filename)))))

(defun fzf-search-git-files ()
  (interactive)
  (let ((process-environment (append '("FZF_DEFAULT_COMMAND=git ls-files")
                                     process-environment))
        (default-directory (utils--get-project))
        (tmp-filename (make-temp-file "fzf-"))
        (tmp-buffer (make-temp-name "fzf-"))
        (previous-vterm-shell vterm-shell))
    (switch-to-buffer tmp-buffer)
    (setq vterm-shell (format "fzf -m >%s" tmp-filename))
    (vterm-mode)
    (set-process-sentinel (get-buffer-process tmp-buffer) 'fzf--sentinel)
    (setq-local fzf--filename tmp-filename)
    (setq-local fzf--path default-directory)
    (setq vterm-shell previous-vterm-shell)))

(defun fzf-search-files ()
  (interactive)
  (let ((default-directory (utils--get-project))
        (tmp-filename (make-temp-file "fzf-"))
        (tmp-buffer (make-temp-name "fzf-"))
        (previous-vterm-shell vterm-shell))
    (switch-to-buffer tmp-buffer)
    (setq vterm-shell (format "fzf -m >%s" tmp-filename))
    (vterm-mode)
    (set-process-sentinel (get-buffer-process tmp-buffer) 'fzf--sentinel)
    (setq-local fzf--filename tmp-filename)
    (setq-local fzf--path default-directory)
    (setq vterm-shell previous-vterm-shell)))

(provide 'fzf)
