{
  imports = [
    ./dnsmasq.nix
    ./docker.nix
    ./documentation.nix
    ./emacs.nix
    ./git.nix
    ./gui.nix
    ./log-activity.nix
    ./mail.nix
    ./modem.nix
    ./neovim.nix
    ./network.nix
    ./oom.nix
    ./parity.nix
    ./rpi3bp.nix
    ./shell.nix
    ./ssh.nix
    ./steam.nix
    ./tor.nix
    ./users.nix
    ./virt.nix
    ./zeronet.nix
  ];
}
